/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-dynamixel-motor-0.2.3/debian/ros-groovy-dynamixel-motor/opt/ros/groovy/stacks/dynamixel_motor/dynamixel_msgs/msg/MotorState.msg */
#ifndef DYNAMIXEL_MSGS_MESSAGE_MOTORSTATE_H
#define DYNAMIXEL_MSGS_MESSAGE_MOTORSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace dynamixel_msgs
{
template <class ContainerAllocator>
struct MotorState_ {
  typedef MotorState_<ContainerAllocator> Type;

  MotorState_()
  : timestamp(0.0)
  , id(0)
  , goal(0)
  , position(0)
  , error(0)
  , speed(0)
  , load(0.0)
  , voltage(0.0)
  , temperature(0)
  , moving(false)
  {
  }

  MotorState_(const ContainerAllocator& _alloc)
  : timestamp(0.0)
  , id(0)
  , goal(0)
  , position(0)
  , error(0)
  , speed(0)
  , load(0.0)
  , voltage(0.0)
  , temperature(0)
  , moving(false)
  {
  }

  typedef double _timestamp_type;
  double timestamp;

  typedef int32_t _id_type;
  int32_t id;

  typedef int32_t _goal_type;
  int32_t goal;

  typedef int32_t _position_type;
  int32_t position;

  typedef int32_t _error_type;
  int32_t error;

  typedef int32_t _speed_type;
  int32_t speed;

  typedef double _load_type;
  double load;

  typedef double _voltage_type;
  double voltage;

  typedef int32_t _temperature_type;
  int32_t temperature;

  typedef uint8_t _moving_type;
  uint8_t moving;


  typedef boost::shared_ptr< ::dynamixel_msgs::MotorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_msgs::MotorState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MotorState
typedef  ::dynamixel_msgs::MotorState_<std::allocator<void> > MotorState;

typedef boost::shared_ptr< ::dynamixel_msgs::MotorState> MotorStatePtr;
typedef boost::shared_ptr< ::dynamixel_msgs::MotorState const> MotorStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dynamixel_msgs::MotorState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dynamixel_msgs::MotorState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dynamixel_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dynamixel_msgs::MotorState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dynamixel_msgs::MotorState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_msgs::MotorState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1cefdc3ff0c7d52e475886024476b74d";
  }

  static const char* value(const  ::dynamixel_msgs::MotorState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1cefdc3ff0c7d52eULL;
  static const uint64_t static_value2 = 0x475886024476b74dULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_msgs::MotorState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_msgs/MotorState";
  }

  static const char* value(const  ::dynamixel_msgs::MotorState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_msgs::MotorState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 timestamp   # motor state is at this time\n\
int32 id            # motor id\n\
int32 goal          # commanded position (in encoder units)\n\
int32 position      # current position (in encoder units)\n\
int32 error         # difference between current and goal positions\n\
int32 speed         # current speed (0.111 rpm per unit)\n\
float64 load        # current load - ratio of applied torque over maximum torque\n\
float64 voltage     # current voltage (V)\n\
int32 temperature   # current temperature (degrees Celsius)\n\
bool moving         # whether the motor is currently in motion\n\
\n\
";
  }

  static const char* value(const  ::dynamixel_msgs::MotorState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dynamixel_msgs::MotorState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dynamixel_msgs::MotorState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.timestamp);
    stream.next(m.id);
    stream.next(m.goal);
    stream.next(m.position);
    stream.next(m.error);
    stream.next(m.speed);
    stream.next(m.load);
    stream.next(m.voltage);
    stream.next(m.temperature);
    stream.next(m.moving);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MotorState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_msgs::MotorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dynamixel_msgs::MotorState_<ContainerAllocator> & v) 
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "goal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
    s << indent << "error: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error);
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "load: ";
    Printer<double>::stream(s, indent + "  ", v.load);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    s << indent << "temperature: ";
    Printer<int32_t>::stream(s, indent + "  ", v.temperature);
    s << indent << "moving: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moving);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_MSGS_MESSAGE_MOTORSTATE_H

