/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-dynamixel-motor-0.2.3/debian/ros-groovy-dynamixel-motor/opt/ros/groovy/stacks/dynamixel_motor/dynamixel_controllers/srv/SetComplianceMargin.srv */
#ifndef DYNAMIXEL_CONTROLLERS_SERVICE_SETCOMPLIANCEMARGIN_H
#define DYNAMIXEL_CONTROLLERS_SERVICE_SETCOMPLIANCEMARGIN_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace dynamixel_controllers
{
template <class ContainerAllocator>
struct SetComplianceMarginRequest_ {
  typedef SetComplianceMarginRequest_<ContainerAllocator> Type;

  SetComplianceMarginRequest_()
  : margin(0)
  {
  }

  SetComplianceMarginRequest_(const ContainerAllocator& _alloc)
  : margin(0)
  {
  }

  typedef uint8_t _margin_type;
  uint8_t margin;


  typedef boost::shared_ptr< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetComplianceMarginRequest
typedef  ::dynamixel_controllers::SetComplianceMarginRequest_<std::allocator<void> > SetComplianceMarginRequest;

typedef boost::shared_ptr< ::dynamixel_controllers::SetComplianceMarginRequest> SetComplianceMarginRequestPtr;
typedef boost::shared_ptr< ::dynamixel_controllers::SetComplianceMarginRequest const> SetComplianceMarginRequestConstPtr;


template <class ContainerAllocator>
struct SetComplianceMarginResponse_ {
  typedef SetComplianceMarginResponse_<ContainerAllocator> Type;

  SetComplianceMarginResponse_()
  {
  }

  SetComplianceMarginResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetComplianceMarginResponse
typedef  ::dynamixel_controllers::SetComplianceMarginResponse_<std::allocator<void> > SetComplianceMarginResponse;

typedef boost::shared_ptr< ::dynamixel_controllers::SetComplianceMarginResponse> SetComplianceMarginResponsePtr;
typedef boost::shared_ptr< ::dynamixel_controllers::SetComplianceMarginResponse const> SetComplianceMarginResponseConstPtr;

struct SetComplianceMargin
{

typedef SetComplianceMarginRequest Request;
typedef SetComplianceMarginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetComplianceMargin
} // namespace dynamixel_controllers

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daacbf1c0642fe923f2dfb9217a97b81";
  }

  static const char* value(const  ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdaacbf1c0642fe92ULL;
  static const uint64_t static_value2 = 0x3f2dfb9217a97b81ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_controllers/SetComplianceMarginRequest";
  }

  static const char* value(const  ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
uint8 margin\n\
\n\
";
  }

  static const char* value(const  ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_controllers/SetComplianceMarginResponse";
  }

  static const char* value(const  ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.margin);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetComplianceMarginRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetComplianceMarginResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<dynamixel_controllers::SetComplianceMargin> {
  static const char* value() 
  {
    return "daacbf1c0642fe923f2dfb9217a97b81";
  }

  static const char* value(const dynamixel_controllers::SetComplianceMargin&) { return value(); } 
};

template<>
struct DataType<dynamixel_controllers::SetComplianceMargin> {
  static const char* value() 
  {
    return "dynamixel_controllers/SetComplianceMargin";
  }

  static const char* value(const dynamixel_controllers::SetComplianceMargin&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daacbf1c0642fe923f2dfb9217a97b81";
  }

  static const char* value(const dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_controllers/SetComplianceMargin";
  }

  static const char* value(const dynamixel_controllers::SetComplianceMarginRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daacbf1c0642fe923f2dfb9217a97b81";
  }

  static const char* value(const dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_controllers/SetComplianceMargin";
  }

  static const char* value(const dynamixel_controllers::SetComplianceMarginResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_CONTROLLERS_SERVICE_SETCOMPLIANCEMARGIN_H

